### ISSUE TITLE
Default datestamp used as title not filename

### ISSUE THREAD

**Issue by jgclark** [kopischke/mmd2en#1]
On quite a few files added using the "Open ..." command from the app (or dropping it onto the app icon), it fails to use the filename as the title, instead defaulting to the current datestamp. I suspect this is happening when the MD or MMD contents of the file are in UTF-16 not ASCII or UTF-8.

I believe this is connected with Issue #2.

**Comment by kopischke** [comment]
Thanks for participating in the beta and filing this issue. Could you please provide me with both
1. a file for wich the note title is set as expected, and
2. a file for which it is not, i.e. the date stamp is used

either as a downloadable archive somewhere (Dropbox. CloudApp, Droplr, whatever works for you) or via the email address listed on the [Contact section of the wiki](https://github.com/kopischke/mmd2en/wiki/Project-Information#%23giving-non-bug-feedback)?

**Comment by jgclark** [comment]
Examples now uploaded: 

File that produces the expected title: https://www.dropbox.com/s/7mozsjyse7ocel1/Lessons%20from%20real%20conversations%20about%20the%20Gospel%20-%20Case%20Six%20%28Brian%20Draper%2C%202006%29.mmd
File that doesn't: https://www.dropbox.com/s/a5pzqy28v3c97f1/Alpha%2015%20-%20Suffering%20and%20the%20Problem%20of%20Evil.md

**Comment by kopischke** [comment]
Thanks for the upload – I’ll take a look at the files tomorrow.

**Comment by kopischke** [comment]
Your files confirmed my suspicion these are two issues mixed up with each other:
1. **the title default fallback strategy**: currently, that does not take account of the file name. What is used when there is no _explicit title metadata in the file contents_ is the H1 heading of the generated HTML. In the case of your first upload, that happens to match the file name so the result is, practically speaking, identical.
2. **the unability to process UTF-16 files**, including metadata, (issue #2), which, in the case of your second upload, means the default fallback is the timestamp, as described above.

As the behavior of 1. is “as designed” and 2. is covered by another bug already, I will close this issue. I have, however, added a feature request issue for processing file system metadata (issue #4) and will try to land that feature in the next RC. Feel free to pitch in over there if you have suggestions!
