### ISSUE TITLE
Text file import has timestamp note name

### ISSUE THREAD

**Issue by jgclark** [kopischke/mmd2en#3]
I can't drag a .txt file (whether containing MD or not) to the app icon, but I can use the "Open ..." command in the File menu to open the same .txt file. The text is imported OK, but the note's title is set to the current timestamp, not the filename, as is used for other file types.

It would also make sense to allow .txt files to be dropped onto the app icon, given they can be processed OK.

**Comment by kopischke** [comment]
Thanks for participating in the beta and filing this issue. This report is a bit of a hybrid as far as I can see, as it compounds several different topics, one of them being issue #1 (the note title part). I’d like to clear that one up before I delve any further into the other topics mentioned here.

**Comment by jgclark** [comment]
This is different from Issue #1, as the text is imported OK. For example, https://www.dropbox.com/s/0xfsjb5texsxawb/Judges%20Overview%20-%20Marc%20Baker%2C%20Sep%202011.txt, which is an ASCII file containing MD, is imported as a MD file if opened from the File -> Open ... menu. But the note name is the current datestamp.

**Comment by kopischke** [comment]
Thanks for the extra details; I’ll take a look at the file tomorrow.

**Comment by kopischke** [comment]
This is “as designed” as of the current implementation, as your file neither contains explicit title metadata, nor a level 1 heading – the top heading is level 2 (see issue #1, point 1. for an explanation and issue #4 for a feature request resolving this). Closing as duplicate.
