### ISSUE TITLE
How Do I Use mmd2en?

### ISSUE THREAD

**Issue by manishsuwal** [kopischke/mmd2en#6]
I'm having difficulty understand how to use this. 

I want to be able to create Evernote notes through Markdown or through terminal (command line). I researched and reached here. 

I downloaded the MMD2EN but have no idea how to use this or what to do with it.

I have it on my dock, but nothing opens while I click on it:
![screen shot 2014-07-10 at 3 11 56 pm](https://cloud.githubusercontent.com/assets/5318719/3536661/67de8e10-0814-11e4-8647-b28a3bd71f8f.png)

Sorry for the basic question.

**Comment by paulelms** [comment]
For example, you can open markdown document with this app and it appear in evernote.
Also, try http://www.geeknote.me

**Comment by jgclark** [comment]
I remember feeling uncertain how to use this the first time as well.
Perhaps there could be a clearer note about this in the Help?

What I do is start the app, and then drag and drop one or more files onto
its icon in the dock. But you can also Open files from the File menu, which
does the same job. That's really all there is to it.

-- Jonathan

On Thursday, July 10, 2014, Manish Suwal notifications@github.com wrote:

> I'm having difficulty understand how to use this.
> 
> I want to be able to create Evernote notes through Markdown or through
> terminal (command line). I researched and reached here.
> 
> I downloaded the MMD2EN but have no idea how to use this or what to do
> with it.
> 
> I have it on my dock, but nothing opens while I click on it:
> [image: screen shot 2014-07-10 at 3 11 56 pm]
> https://cloud.githubusercontent.com/assets/5318719/3536661/67de8e10-0814-11e4-8647-b28a3bd71f8f.png
> 
> Sorry for the basic question.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kopischke/mmd2en/issues/6.

## 

Thanks,

-- Jonathan

**Comment by kopischke** [comment]
Besides being abled to open Markdown documents with the app (either via the “Open in” context menu in Finder, or by dropping them onto the Dock icon, you should also have two new OS X Services: one for selected text, and one for Markdown files (may need to be activated in keyboard system preferences). But better docs would help, yeah. One more item for my to do list.

**Comment by manishsuwal** [comment]
After reading these comments I understood how to use **mmd2en**. Basically, I have to write in Markdown editor and drag it on **mmd2en**. The concept is amazing. 

From now, I can consider writing in markdown for Evernote. YIPPIE!

@vyazovoi thank you for linking [geeknote](http://geeknote.me). That's exactly what I was looking for. I'm using it right now and love it!
